GET http://localhost:5000/products

###
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "boniato espacial",
  "price": 3000,
  "promoPrice": 1500,
  "discountPercentage": 0,
  "weight": 1000,
  "category": "verduras",
  "available": true,
  "img": "https://www.eltiempo.com/files/article_content/uploads/2019/08/27/5d65a4c5b5f5e.jpeg"
}
###
PATCH  http://localhost:5000/products/24
Content-Type: application/json

{
  "name": "modificado",
  "promoPrice": 9,
  "weight": 1200,
  "category": "verduras",
  "img": "https://www.eltiempo.com/files/article_content/uploads/2019/08/27/5d65a4c5b5f5e.jpeg"
}
###
DELETE http://localhost:5000/products/3